### ISSUE TITLE
Can't load Halo 5 MP armour render model

### ISSUE THREAD

**Issue by masterj2001** [Gravemind2401/Reclaimer#10]
So when trying to open the storm_masterchief render model file in the Halo 5 Forge model module, it loads for a bit and then displays nothing to the right of the files list, doesn't even create a model viewer tab.

The image below is the error that appears when trying to load this render model. The same error is thrown when trying to open the knight render model in the Halo 5 LAN model module.
![image](https://user-images.githubusercontent.com/86584252/123577577-434c8a80-d813-11eb-96b3-b6ac86ab9f3f.png)

**Comment by Gravemind2401** [comment]
The knight will be fixed for the next update. The storm_spartans model is more complicated as its stored differently to other models and has 4000 blocks of resource data to work with instead of the usual 1. I'm not sure what I can do with that yet.

**Comment by Gravemind2401** [comment]
It’s been a while, but this will be addressed in the next major update (though there is no time frame for that yet).
If you are familiar with compiling code, there’s a WIP branch called `h5stuff` where this is currently possible.

**Comment by Gravemind2401** [comment]
This has now been resolved in the latest build.
