### ISSUE TITLE
Some, Halo 5 Server Bitmaps not opening or exporting

### ISSUE THREAD

**Issue by Baconator650** [Gravemind2401/Reclaimer#11]
Few, but not all bitmaps are not exporting or opening. Looks to predominantly bitmap associated with Warzone or Campaign.

![image](https://user-images.githubusercontent.com/78010776/123706405-ddb9c780-d82d-11eb-9b6a-0fc25f1c0ad1.png)

**Comment by Gravemind2401** [comment]
A majority of the bitmap tags on Halo 5 Server don't have any resource data. Only a handful of UI related bitmaps actually have data.
