### ISSUE TITLE
Some Halo 2 UI bitmaps not parsing correctly

### ISSUE THREAD

**Issue by 2Tie** [Gravemind2401/Reclaimer#17]
There are a few bitmap resources in both Halo 2 xbox and Halo 2 Beta that don't render correctly; on retail, textures like ui\global_bitmaps\temp\map_c_the_dervish.bitmap or ui\screens\game_shell\load_level\load_level.bitmap in mainmenu.map or something like scenarios\test\meat_grinder\jackal_test\bitmaps\jackal_shield_mask.bitmap in the beta are all getting parsed to the right number of images, but the displayed images are all distorted, sliding off to one side the farther you get down them.

**Comment by Gravemind2401** [comment]
This should now be resolved as of v1.7.310.
