### ISSUE TITLE
H2A MP map loading broken

### ISSUE THREAD

**Issue by chipsnapper** [Gravemind2401/Reclaimer#18]
Hi, I'm not sure if the 2021-11-03 MCC update broke it, but H2A MP maps are not opening in the current version of Reclaimer.

**Comment by Gravemind2401** [comment]
Yes, it was the MCC update - Reclaimer only supports files that exist at the time it gets updated. Each time MCC has an update and changes the files it will prevent Reclaimer from recognizing them and another update has to be done to add them.

Reclaimer has now been updated to support the latest MCC update.
