### ISSUE TITLE
Unable to open maps from Halo Reach

### ISSUE THREAD

**Issue by Toasterblast** [Gravemind2401/Reclaimer#19]
I've been trying to open a Halo Reach map and it doesn't work. Halo 3 and Halo CE work just fine, and I don't have 2, ODST, or 4. Multiple maps have been attempted and they all give this error. I have the latest version of Reclaimer installed and I've even restarted my PC a few times. 
![image](https://user-images.githubusercontent.com/80008100/141645426-d0766837-ad5b-4777-8dd9-7c2f71e176d4.png)

**Comment by Gravemind2401** [comment]
MCC was updated this month which included changes to the Reach maps. Each time MCC has an update and maps get modified it will prevent Reclaimer from recognizing them until an update is done to add support for the changes.

Reclaimer has now been updated to support the latest MCC update including support for the changes made to the Reach maps.
