### ISSUE TITLE
reclaimer.setup.vdproj not admited neither in VS 2017 nor VS 2019

### ISSUE THREAD

**Issue by TheThouZands** [Gravemind2401/Reclaimer#20]
in both versions it says: "_The project types may not be installed or may not be compatible with this version of Visual Studio._"
**Maybe** am i missing something? do i need to install any plugin?, what verion of vs must i use?

**Comment by Gravemind2401** [comment]
The installer project requires the Visual Studio extension "Visual Studio Installer Projects". That project is not required for building though so you can just leave it unloaded if you want.
