### ISSUE TITLE
Raw export?

### ISSUE THREAD

**Issue by CosmicDreamsOfCode** [Gravemind2401/Reclaimer#21]
Hi, I'm trying to rip the wwise soundbanks from Halo 4 but the tool doesn't seem to support exporting anything other than what it can convert. An option to dump anything from the files unconverted would be very useful.
This will also apply to Infinite if support gets added for that game at any point.

**Comment by Gravemind2401** [comment]
In the app settings there is the option to extract sounds without conversion, however Halo 4 is not supported for sound extraction.
