### ISSUE TITLE
Reclaimer no longer opens map files

### ISSUE THREAD

**Issue by TravieRulezd00d** [Gravemind2401/Reclaimer#25]
Trying to open up map files results in an error code.

**Comment by Waffle1434** [comment]
+1

**Comment by Max585t** [comment]
+1

**Comment by lambsie11** [comment]
Hmm... Might be due to the flood firefight update that just came out.

**Comment by Gravemind2401** [comment]
Each time there is a title update Reclaimer needs to be updated to add support for the new version.
Reclaimer has since been updated to support the recent MCC update, excluding H4 and H2AMP.
