### ISSUE TITLE
Halo 4

### ISSUE THREAD

**Issue by FosterWood** [Gravemind2401/Reclaimer#26]
While the new update fixed Halo 3 and Reach's maps not opening, the update didn't fix Halo 4's maps not reading.

**Comment by Jake-Boraman** [comment]
...and it never claimed to

**Comment by Gravemind2401** [comment]
Halo 4 and Halo 2A MP were not included as part of the last Reclaimer update as they had more significant changes than the others and will take some more time to sort out.
