### ISSUE TITLE
H2A MP maps fail to open

### ISSUE THREAD

**Issue by Rodolfo-Bevione** [Gravemind2401/Reclaimer#29]
Opening H2A map files from the updated MCC version for PC causes "unable to load file.map", on Reclaimer version 1.7.800

![image](https://user-images.githubusercontent.com/26967928/177225513-1257163b-ed8d-4eb1-9e7d-f67dac728282.png)

What's the correct way to handle this? Thanks for reading

**Comment by Gravemind2401** [comment]
Each time there is an update to MCC that modifies any of the map files they will no longer work in Reclaimer until it is updated to support the new version.
The latest Reclaimer release should now support the most recent H2AMP and H4 changes.
