### ISSUE TITLE
Halo 3 warehouse.map door_blocker_medium broken

### ISSUE THREAD

**Issue by bloodyPRAT** [Gravemind2401/Reclaimer#3]
Can't open the file to view any of the files

**Comment by Gravemind2401** [comment]
If you are referring to there being nothing visible for this model in the model viewer then that was specific to the Architect model viewer and has been resolved as of Architect [v1.4.183](https://github.com/Gravemind2401/Reclaimer.Architect/releases/latest).
If you are referring to something else please provide more detail.

**Comment by bloodyPRAT** [comment]
Probably because I didn’t update to the newer version of Architect, thanks
will keep you informed if I find more bugs in furtive updates
