### ISSUE TITLE
Unable to add Blender AMF2 add-in to Blender 2.79

### ISSUE THREAD

**Issue by Cealach** [Gravemind2401/Reclaimer#32]
Blender is throwing an error when I try to load the add-in:

![image](https://user-images.githubusercontent.com/119283484/204209574-541e12e8-32ee-4ace-abfd-74134ab8fd79.png)

**Comment by Gravemind2401** [comment]
The AMF2 add-in requires Blender v2.80 or higher, as it uses Python features that are not available in earlier versions.
