### ISSUE TITLE
Reclaimer crashes when trying to open a render_model or bitmap on Halo 4

### ISSUE THREAD

**Issue by joeyeroq** [Gravemind2401/Reclaimer#33]
v1.7.823 Reclaimer crashes when trying to open a render_model or bitmap on Halo 4, the previous Reclaimer v1.7.808 works.
I want to test this new version of Reclaimer because it reportedly can export multiple uv maps.

**Comment by Gravemind2401** [comment]
This is due to the recent MCC update. The latest Reclaimer build should resolve this.
