### ISSUE TITLE
Can't open Halo 1 map models

### ISSUE THREAD

**Issue by Overdoziz** [Gravemind2401/Reclaimer#35]
I can't seem to open Halo 1 map models in the viewer. Halo Reach ones work fine, but the Halo 1 scenario_structure_bsp files do nothing.

**Comment by Gravemind2401** [comment]
BSPs are not currently supported for MCC Halo CE maps. For Halo CE, currently only the original PC and Custom Edition maps have support for `scenario_structure_bsp` tags.
