### ISSUE TITLE
Crash on "View -> App Directory"

### ISSUE THREAD

**Issue by realS47** [Gravemind2401/Reclaimer#36]
Pretty much exactly what it sounds like. On a fresh install of the latest version of Reclaimer, .NET 6, and a restart of my computer, I opened up Reclaimer, went to "View -> App Directory", and after about a second, the program crashes with nothing else pulled up.

I'm running this on Windows 11.

Not sure if there was something I missed.

**Comment by MathiusXII** [comment]
Same

**Comment by Gravemind2401** [comment]
This should now be resolved. Note that this issue also affects the 'Download' button in the update details window so you may need to manually open the download page at https://github.com/Gravemind2401/Reclaimer/releases/tag/v1.7.829 rather than using the download button in the app.

**Comment by realS47** [comment]
That did the trick. Thank you very much!
