### ISSUE TITLE
Latest release application won't launch (v1.7.832)

### ISSUE THREAD

**Issue by elusians** [Gravemind2401/Reclaimer#39]
Hello, 

I can't actually seem to launch the executable in the latest release, no error involved, application attempts to load but nothing actually happens.

I can confirm that I can run the previous build [v1.7.829](https://github.com/Gravemind2401/Reclaimer/releases/tag/v1.7.829) with no issues however. I am running the application on Windows 10 22H2(OS Build 19045.2486)

I'm not really sure what other information to provide, but let me know if there is anything else you need.

**Comment by chipsnapper** [comment]
Same issue here, I have Dotnet 6 and 7 32/64 bit and the SDKs installed

**Comment by Gravemind2401** [comment]
It turns out there was an issue with the 832 MSI installer not updating all the files correctly. I have added a new build (833) to resolve the problems with the installer.
