### ISSUE TITLE
The file 's3d_waterfall.map' cannot be opened as a map. It is invalid or unsupported.

### ISSUE THREAD

**Issue by Buck367** [Gravemind2401/Reclaimer#4]
This has occurred on every map file in the MCC folder. I've verified file integrity with Steam and have reinstalled Reclaimer twice. This has been happening around the time of the Raven update.

Any assistance would be very much appreciated!

**Comment by Gravemind2401** [comment]
When there's an update to MCC there's no guarantee that Reclaimer will be compatible with the update. In this case, Reclaimer had to be updated to work with the most recent version of MCC. This was part of the v1.5.245 update.
Reclaimer will display the version number in the top right - please confirm it is 1.5.245 or newer. The newest is currently 1.5.250 which can be downloaded in the [releases](https://github.com/Gravemind2401/Reclaimer/releases/latest) section.

**Comment by Buck367** [comment]
Thanks a bunch, worked like a charm!
