### ISSUE TITLE
Error when importing AMF files into Blender. Also deletes existing model

### ISSUE THREAD

**Issue by SgtFlex** [Gravemind2401/Reclaimer#40]
Sorry, not sure if I missed an important detail, but I copy-pasted the script into blender and ran it, and it throws an error and deletes existing models in the scene. It still successfully imports the model upon completing the dialogue that opens, but I don't know if the error is what's causing the existing models to get deleted or if its just a quirk of the script that needs to be worked around.

`Python: Traceback (most recent call last):
  File "C:\Users\sgtfl\OneDrive\Documents\Blender\scenes\Grunt01.blend\ReclaimerImport", line 943, in <module>
  File "C:\Users\sgtfl\OneDrive\Documents\Blender\scenes\Grunt01.blend\ReclaimerImport", line 936, in unregister
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)
`

**Comment by Gravemind2401** [comment]
The Blender script is designed to be imported as an addon. Its set up to be more like a test mode if you run it from the script editor so it will clear out the scene first.
You can install it as an addon by going to `Edit > Preferences` then click 'Install' and browse for the script. It should then appear in the addons list where you can enable/disable it. When enabled, it adds an AMF option under the `File > Import` menu.
