### ISSUE TITLE
having an issue with extracting audio files 

### ISSUE THREAD

**Issue by IcyCarbide** [Gravemind2401/Reclaimer#46]
below is the issue, it seems to be something about ffmpeg (which I do have installed) I wnat to get some audio files from the halo3 odst map files

Loading plugin Reclaimer [Reclaimer]
Loading plugin Reclaimer.Plugins.BatchExtractPlugin [Batch Extractor]
Loading plugin Reclaimer.Plugins.BitmapViewerPlugin [Bitmap Viewer]
Loading plugin Reclaimer.Plugins.MapViewerPlugin [Map Viewer]
Loading plugin Reclaimer.Plugins.ModelViewerPlugin [Model Viewer]
Loading plugin Reclaimer.Plugins.ModuleViewerPlugin [Module Viewer]
Loading plugin Reclaimer.Plugins.PakViewerPlugin [Pak Viewer]
Loading plugin Reclaimer.Plugins.SoundExtractorPlugin [Sound Extractor]
Could not load plugin Reclaimer.Plugins.SoundExtractorPlugin [Sound Extractor]
System.IO.FileNotFoundException: FFmpeg is required for sound conversion but was not found.
   at Reclaimer.Plugins.SoundExtractorPlugin.Initialise() in X:\Documents\Visual Studio 2022\Projects\Reclaimer.Build\Reclaimer\Reclaimer\Plugins\SoundExtractorPlugin.cs:line 34
   at Reclaimer.Plugins.Substrate.LoadPlugins() in X:\Documents\Visual Studio 2022\Projects\Reclaimer.Build\Reclaimer\Reclaimer\Plugins\Substrate.cs:line 95
Loading plugin Reclaimer.Plugins.MetaViewer.MetaViewerPlugin [Meta Viewer]
No handler found for file: C:\Program Files (x86)\Gravemind2401\Reclaimer\Reclaimer.dll

**Comment by Gravemind2401** [comment]
Have you set the ffmpeg path in the settings? Once ffmpeg is downloaded, you also need to put that path to it into the settings so Reclaimer so it knows where to find the ffmpeg exe. From `Tools > Settings` you can open the settings panel, then select `Sound Extractor` in the dropdown at the top and update the `FFmpeg Path` setting.

**Comment by IcyCarbide** [comment]
the setting "Sound Extractor" does not come up in my settings

**Comment by Gravemind2401** [comment]
I looked into this further and realized its a chicken-and-egg situation - you cant set the FFmpeg path because the sound extractor isn't loaded, and the sound extractor won't load because FFmpeg isn't found. I will need to change how that works in a future update.

For now, if you place it in the default location then it should work;
1. From the menu, click `View > App Directory`
2. In the folder that gets opened, create a `Plugins` folder if there isn't one already
3. In the `Plugins` folder, create a folder called `ffmpeg`
4. Place `ffmpeg.exe` inside the `ffmpeg` folder

**Comment by IcyCarbide** [comment]
I tried doing what you said and the "Sound Extractor" does come up in settings but still won't open/extract anything
does "No handler found for file: C:\Program Files (x86)\Gravemind2401\Reclaimer\Reclaimer.dll" mean anything?

**Comment by Gravemind2401** [comment]
That particular error can be ignored.
What maps are you using? Sound extraction is only supported for H3/ODST/Reach and only with the Xbox 360 map files.

**Comment by Gravemind2401** [comment]
The issue with not being able to set the ffmpeg path setting has now been resolved in the latest build.
