### ISSUE TITLE
Using Reclaimer v1.6.250, and getting a error when trying to open any Halo 2 maps, even though the latest update for Reclaimer said it was now fully able to support opening the file types for Halo 2? 

### ISSUE THREAD

**Issue by flipdark95** [Gravemind2401/Reclaimer#5]
Hey, I'm getting a error when trying to open any Halo 2 maps, even though the latest update for Reclaimer said it was now fully able to support opening the file types for Halo 2? 

I'm using the latest version of Reclaimer, and have a legitimate steam copy of Halo MCC that's updated to the latest version.

**Comment by Gravemind2401** [comment]
If you are referring to Halo 2 campaign maps, or the original Halo 2 multiplayer maps, they are not supported. The last updated added support for Halo 2 Anniversary Multiplayer which is the maps in the groundhog folder.

**Comment by flipdark95** [comment]
Ah, got it. Thanks very much :)
