### ISSUE TITLE
[H5] [Feature Request] View render models with overlap after linking

### ISSUE THREAD

**Issue by Zidiath** [Gravemind2401/Reclaimer#53]
Less a bug I suppose, however something I have noticed that when you load up modules for Halo 5. Even when linking every other module with say globals-rtx-1 it will only show the initial render model for an item even if another version of said render model is included in another module (hard to explain but ill give an example)

If you load up globals-rtx-1.module and link every other module to it you'll get the following model for the wasp.

![image](https://github.com/Gravemind2401/Reclaimer/assets/13132499/27f9c30c-3d44-4193-95ec-eec876b239e9)

However, if you load up say load up just globals-rtx-77316-3 you'll see a completely different (the final version) of the wasp available. 

![image](https://github.com/Gravemind2401/Reclaimer/assets/13132499/b849de30-58cf-4469-ab8c-050b4c1337ca)

Would it be a possible feature request in the future that if it detects say a different amount of vertices in the model of another module it also makes it available in the full list? (I apologies if this is outside the realm of possibility.)

**Comment by Gravemind2401** [comment]
While it won’t load all the models in the same model viewer tab, you should be able to right-click the tag and use the `Open From` menu to select a specific linked module to load it from. This menu only appears if you have linked modules and only when the tag exists in more than one of them.
It won’t open the same tag in the model viewer more than once though, so I don’t think you’ll be able to open all versions of the model at the same time.
