### ISSUE TITLE
Cannot Open Program

### ISSUE THREAD

**Issue by KoviBat** [Gravemind2401/Reclaimer#56]
I downloaded the latest version of Reclaimer (v1.7.836) and I am unable to launch the program at all. Double-clicking, right-clicking and selecting open, and even Run As Administrator results in nothing happening. I've installed .NET 7 Runtime as suggested by someone else but I still have the same issue. If you can help me figure out what I'm doing wrong I would be very grateful.

**Comment by Gravemind2401** [comment]
The current version of Reclaimer needs the .NET 6 Desktop Runtime, not 7. Try installing that, and if it still doesn't start you may need to check the Windows Event Viewer to see what the error is.

**Comment by KoviBat** [comment]
That solved the issue, thank you, and sorry for bothering you
