### ISSUE TITLE
Unable To Open MCCH3 Steam Workshop Maps

### ISSUE THREAD

**Issue by Insan1ty0ne** [Gravemind2401/Reclaimer#57]
Q: What version of Reclaimer are you using?
A: v1.7.838
Q: What game are you trying to open them from?
A: Halo 3 MCC
Q: What map file are you using?
A: .map file sourced from this mod: [https://steamcommunity.com/sharedfiles/filedetails/?id=3005097470](url)
Q: What is happening when you try to open the .map? Does it do nothing, is there an error message, does the model viewer tab open?
A: The following error message displays: "Unable to load (name).map: The file `name.map` cannot be opened. It looks like a valid map file, but may not be a supported version." Nothing else happens.

**Comment by Gravemind2401** [comment]
These maps should now work in the latest build.
