### ISSUE TITLE
[H5] [Feature Request] Exporting .bitmap files as their raw file with chunk files for unswizzling via external programs

### ISSUE THREAD

**Issue by TacoHombre** [Gravemind2401/Reclaimer#59]
For the campaign files it's a pain to extract all the modules manually, would be super convenient for reclaimer to be able to export the raw .bitmap files with the chunk files for ease of conversion. Bonus if it can be batched as well

**Comment by Gravemind2401** [comment]
The latest version of the `h5stuff` branch lets you dump the resource chunks using the right-click menu in the tag list. It also does regular tags as well.
