### ISSUE TITLE
MCC Halo 4 Sound extraction

### ISSUE THREAD

**Issue by VpSnipes** [Gravemind2401/Reclaimer#60]
Sound files from the MCC version of Halo 4 do not properly extract, and do not write files. Halo 4 from the Xbox 360 does not properly grab the entire sound structure either and will only write specific files leaving out a BULK MAJORITY of files (most with poor compression likely due to the compression of Xbox 360)

**Comment by Gravemind2401** [comment]
Reclaimer's sound extraction currently only supports Halo3, ODST and Reach and only when using the Xbox 360 files. Halo 1, 2, 4 and MCC are not currently supported.
