### ISSUE TITLE
[H5] Support for binary extraction without structs

### ISSUE THREAD

**Issue by Surasia** [Gravemind2401/Reclaimer#62]
Currently, the "Extract Tag Binary" option is only enabled if the Halo 5 plug-ins are installed, as it's defined in the ModuleViewerPlugin rather than ModuleViewer. This creates the issue of having to dump the tagstructs for each build separately, even though the underlying module structure is the same.

Any option to simply extract any tag defines in the file list would be greatly appreciated.

**Comment by Gravemind2401** [comment]
I'm not sure what you mean by "only enabled if the Halo 5 plug-ins are installed". Are you referring to the meta viewer xml files?
The meta viewer and its xml plugins are separate from the module viewer and the xml files are not required for any functionality other than viewing tag data in the meta viewer.
In the current state of the `h5stuff` branch the `Extract Tag Binary` option should be appearing on any tag or resource chunk shown in the module viewer.
