### ISSUE TITLE
[H5] [Feature Request] Bulk-extract based on highest linked Module

### ISSUE THREAD

**Issue by Zidiath** [Gravemind2401/Reclaimer#63]
Based on my testing the past day or so (Xbox files) I noticed that data in the modules is "progressive" dependent on how high the module number is. For example something in globals-rtx-92607-2 will have "newer" or (generally)more data attached than globals-rtx-1. A few good examples of this can be seen when comparing the file sizes of extracted module data.

![image](https://github.com/Gravemind2401/Reclaimer/assets/13132499/9f40314c-0918-4082-b214-c6935d6517fb)

![image](https://github.com/Gravemind2401/Reclaimer/assets/13132499/19ca8ff5-6236-4487-aa4b-f24cb8461250)

Now comparing the Globals-rtx-1 and Globals-rtx-92607-2 amf files in blender I found that they had object totals of 2,956 and 3,955 respectively (also from a quick overview I noticed DLC content was missing int he Globals-rtx-1).

![image](https://github.com/Gravemind2401/Reclaimer/assets/13132499/91c2be7d-2d67-429e-a725-9667a50041a8)

Further parsing of other render models showed similar outcomes, higher number = newer data.

(Elite had officer_boss variant, Grunt had bodyguard variant, Bishop had Commander_boss) Obviously these 3 examples are simple color swaps but it does show newer data is constantly in the higher number module. 

Another good example of this is the Wasp, similar findings as the storm_masterchief model. Infact if you open the model in number order you'll see it slowly get more and more detail. 

The main feature request from this is in bulk-exporting to have it so (perhaps with an extra check box) it will export the model from the module with the highest number for said model for each model. (If I ran bulk export Wasp would export the model from globals-rtx-91428-2 and storm_masterchief would export the model from globals-rtx-92607-2)

**Comment by Gravemind2401** [comment]
I've updated it to prioritize duplicate tags by module file name descending which should give the desired results.
