### ISSUE TITLE
Plugins don't work on latest build

### ISSUE THREAD

**Issue by wowjinxy** [Gravemind2401/Reclaimer#64]
Plugins don't work on latest build?
I followed the instructions and it doesn't open up the map. According to this Reddit post I'm also not the only person who came across this.

https://www.reddit.com/r/halomods/comments/nf5h5d/reclaimer_no_functions_work/

What's crazy is this post was 3 years ago and it looks like there's still an issue and no one ever reported it?

**Comment by wowjinxy** [comment]
I went version by version to see when the plugin folder stopped showing up.

v1.5.245 = has plugin folder
v1.6.250 = has plugin folder
v1.6.274 = does not
v1.6.285 = does not
v1.6.298 = does not
v1.7.305 = does not
v1.7.800 = does not
v1.7.840 = does not

**Comment by Gravemind2401** [comment]
I’ll have to look into why the plugins folder isn’t created as part of the install, but as a workaround you can just create it manually.

If you’re looking to use Architect though it will only work for Xbox maps, and it may require an older version of Reclaimer to.

**Comment by Gravemind2401** [comment]
This is now resolved in the latest build.
