### ISSUE TITLE
rmf importer dependencies error 

### ISSUE THREAD

**Issue by savinpvtmike** [Gravemind2401/Reclaimer#67]
i get this error when trying to get the dependencies
Command '['C:\\Program Files\\Blender Foundation\\Blender 4.1\\4.1\\python\\bin\\python.exe', '-m', 'pip', 'install', 'PySide2', '--ignore-requires-python']' returned non-zero exit status 1.
even when running as admin

running blender 4.1

**Comment by Gravemind2401** [comment]
This was specific to Blender 4.1 - earlier and later versions both seemed to work correctly.
It should now be resolved with the latest zip files from the beta release.
