### ISSUE TITLE
Data folder constantly changes

### ISSUE THREAD

**Issue by valkyries733** [Gravemind2401/Reclaimer#7]
I set the Data folder to pull from the folder I keep my halo maps in 
I export a model
Then the data folder sets to the folder I just extracted to

Maybe I'm confused, not sure.

Apologies for any misunderstandings lol

**Comment by Gravemind2401** [comment]
Currently it is intentional that if you choose a different folder it will become your new data folder.
I will change it in the next update so it doesn't change automatically, and have a separate option where you can turn on the automatic changes if you wish.
