### ISSUE TITLE
[H5] Some weapon skins are not displayed properly.

### ISSUE THREAD

**Issue by notorangefruit** [Gravemind2401/Reclaimer#72]
Examples:
SMG skin_019 is neon purple in-game but appears as default color in reclaimer.
Magnum skin_040 is neon blue in-game but appears as default color in reclaimer.

Something worth noting is these weapon skins are normally unobtainable in-game unless you equip them via the API.

**Comment by notorangefruit** [comment]
Where can I find this tint value in reclaimer? There are some magnum skins that are currently impossible to equip and I'm curious what tint they have. Also curious if the H2BR has tints.

**Comment by Gravemind2401** [comment]
If you have the meta viewer set up for Halo 5 you can find the tints and other related values in the material tag. For example, in the `smg_skin_019` material tag, I believe the purple tint is from the `surface_color_tint` value. Note that the color values labels are currently incorrect - in Halo 5 the values are in the order of RGBA, not ARGB.
![image](https://github.com/user-attachments/assets/39db0bd0-c899-4a7a-8cca-59bf5e630f01)

**Comment by notorangefruit** [comment]
ARGB looks to be the correct order. 
rgb01(1, 0, 1) #ff00ff is purple.
If I were to use the RGB values in image above, it would be rgb01(1, 1, 0) which is yellow #ffff00
Confirmed same for magnum skin_040 is blue when using ARGB.
