### ISSUE TITLE
Bug: Reclaimer setup only copies over Reclaimer.Core assemblies

### ISSUE THREAD

**Issue by Surasia** [Gravemind2401/Reclaimer#73]
The latest installer (and the one I built using the powershell script) seem to not be copying over anything outside of `Reclaimer.Core.dll` into the install directory, causing the application not to execute.

**Comment by Gravemind2401** [comment]
Is this on a clean install or an upgrade? If its an upgrade, what was the previous version?

MSI installers will usually only replace DLL and EXE files when the installer copy has a higher version number than the existing copy. The PowerShell script to create the installer will set all the version numbers based on the git revision, so if your existing install came from an installer that was created on a different branch with more commits then it may think your existing copy is newer.

**Comment by Surasia** [comment]
This is on a completely clean install, using the setup msi from the releases tab.
