### ISSUE TITLE
not sure. Fresh install

### ISSUE THREAD

**Issue by DirectalArrow** [Gravemind2401/Reclaimer#9]
Loading plugin Reclaimer [Reclaimer]
Loading plugin Reclaimer.Plugins.BatchExtractPlugin [Batch Extractor]
Loading plugin Reclaimer.Plugins.BitmapViewerPlugin [Bitmap Viewer]
Loading plugin Reclaimer.Plugins.ModuleViewerPlugin [Module Viewer]
Loading plugin Reclaimer.Plugins.MapViewerPlugin [Map Viewer]
Loading plugin Reclaimer.Plugins.ModelViewerPlugin [Model Viewer]
Loading plugin Reclaimer.Plugins.PakViewerPlugin [Pak Viewer]
Loading plugin Reclaimer.Plugins.SoundExtractorPlugin [Sound Extractor]
Could not load plugin Reclaimer.Plugins.SoundExtractorPlugin [Sound Extractor]
System.IO.FileNotFoundException: FFmpeg is required for sound conversion but was not found.
   at Reclaimer.Plugins.SoundExtractorPlugin.Initialise()
   at Reclaimer.Plugins.Substrate.LoadPlugins()
Loading plugin Reclaimer.Plugins.MetaViewer.MetaViewerPlugin [Meta Viewer]

downloaded the FFmpeg exe file to see if it fixes anything. Put it with the other dll files. No luck there.
After that i cant use the meta viewer. And it wont load architect with/without it installed.

**Comment by Gravemind2401** [comment]
Architect doesn't require FFmpeg or the meta viewer. If Architect is not opening you may need to right-click the tag and use the `Open With` option.
To set up the meta viewer there's some information on this [wiki page](https://github.com/Gravemind2401/Reclaimer/wiki/Troubleshooting#nothing-happens-when-i-open-a-tag). You need to configure the meta plugins folder in order for the meta viewer to load tags.
